### PR TITLE
Fix setup.py and Python packaging

### PR DESCRIPTION
**Pull request by U039b**

### CODE REVIEW

**Comment by dwisiswant0** [comment]
Please resolve the conflicts.

**Comment by dwisiswant0** [comment]
```console
$ sudo python3.8 setup.py install
$ apkleaks -h
pkg_resources.ResolutionError: Script 'scripts/apkleaks.py' not found in metadata at '/usr/local/lib/python3.8/dist-packages/apkleaks-2.1.0-py3.8.egg/EGG-INFO'
```

**Comment by U039b** [comment]
There is no `scripts/apkleaks.py` defined in `setup.py`, it seems your are not running the code I pushed. BTW I strongly recommend to **never** install WIP packages system-wide. Prefer user-only or virtual environment installation instead.

**Review by dwisiswant0 — APPROVED** [review]
Correct, looks like I forgot to `setup.py build` again. It's legit now.

Thanks for your amazing work!

**Pull request merged**
